### ISSUE TITLE
ability to publish the texturepack as a zip

### ISSUE THREAD

**Issue by NotAShelf** [sachingorkar102/Tweakin-Resource-Pack#1]
g'day, i've created this issue because having to unzip the texturepack before making use of it creates compatibility issues.

if you are a server owner wishing to enforce a texturepack, having the pack in a folder format will ultimately render it un-enforcable

therefore, I was wondering if it is possible to receive the texturepack in a zip format (zipping manually, as you would expect, won't work) to be able to host the texturepack and enforce it

**Comment by sarhatabaot** [comment]
Hi, you can download the whole repo as a zip file by clicking on the "code" button and then "download as zip".
See attached images below: 
![](https://puu.sh/JguoP/7bb729a372.png)

**Comment by NotAShelf** [comment]
> Hi, you can download the whole repo as a zip file by clicking on the "code" button and then "download as zip". See attached images below: ![](https://camo.githubusercontent.com/6f7dcbf9a9f2ac80c60117ad5a8e9f1f058d285c1e7ce7aab7e4e4a8d98515c7/68747470733a2f2f7075752e73682f4a67756f502f376262373239613337322e706e67)

Hey, thanks for the response. But I am very well aware of Github's download ZIP feature.

I don't know what exactly was the issue, but I am quite certain the reason I opened this issue is that the downloaded zip archive would not work, for whatever reason. With that said, I no longer use the resourcepack for Tweakin and this issue is thus obsolete.
